[package]
name = "hff"
version = "0.2.0"
edition = "2021"
authors = ["All8Up <all8up@gmail.com>"]
license-file = "LICENSE"
description = "Hierarchical File Format"
repository = "https://github.com/All8Up/hff.git"
readme = "README.md"

[dependencies]
hff-core = { path = "./crates/hff-core", version = "0.2.0" }
thiserror = "1.0.51"

# Synchronous version.  Always available.
hff-std = { path = "./crates/hff-std", version = "0.2.1" }

# Support for async-std.
async-std = { version = "1.12.0", optional = true }
hff-async-std = { path = "./crates/hff-async-std", version = "0.1.1", optional = true }

# Support for tokio.
# TODO: Minimize the features of tokio for just this crate's needs.
tokio = { version = "1.35.0", features = ["full"], optional = true }
hff-tokio = { path = "./crates/hff-tokio", version = "0.1.1", optional = true }

# Support for serializing serde data into/out of chunks.
# NOTE: The specific content within the data is up to the user.
serde = { version = "1.0.193", features = ["derive"], optional = true }
# Support for compressed chunks.
xz2 = { version = "0.1.7", optional = true }

[features]
default = []
async-std-rt = ["dep:async-std"]
tokio-rt = ["dep:tokio"]
serde = ["dep:serde"]
compression = ["dep:xz2"]
