[package]
name = "hff-std"
version = "0.1.0"
edition = "2021"
authors = ["All8Up <all8up@gmail.com>"]
license-file = "LICENSE"
description = "Hierarchical File Format"
repository = "https://github.com/All8Up/hff.git"
readme = "README.md"

[dependencies]
