[package]
name = "hff-dump"
version = "0.4.0"
edition = "2021"

[dependencies]
hff-std = { version = "0.4.0", features = ["compression"] }
clap = { version = "4.4.13", features = ["derive"] }
byteorder = "1.5.0"
