name: Rust

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (Debug)
      run: cargo build --verbose
    - name: Run tests (Debug)
      run: cargo test --verbose
    - name: Build (Release)
      run: cargo build --verbose --release
    - name: Run tests (Release)
      run: cargo test --verbose --release
